Vcf to table
vertgenlab/gonomics pull request #632
Opened 2022-02-14 21:11 UTC by dasnellings

This PR adds a `-csv` flag to vcfFormat to output vcf records for spreadsheet-based analyses. It turns out to be a fair bit more complicated than it initially seems, but it is working. There are tests, though there are so many corner cases in VCF right now that there are almost certainly some files where this will break.

2022-02-20 02:22 UTC, rimangan commented on cmd/vcfFormat/vcfFormat.go
> +	var outfile *string = flag.String("o", "stdout", "Output file")
I'm not sure I love the default stdout in most cases and would be curious to hear people's thoughts at code review. Certainly inconsistent with the style of much of the code base.

2022-02-20 02:22 UTC, rimangan commented on cmd/vcfFormat/vcfFormat_test.go
> +	"encoding/csv"
not sure if i've seen the csv package in gonomics, nice!

2022-02-21 18:02 UTC, craiglowe approved these changes
This will be nice functionality for people who want to look at VCF data, but are not programmers.

2022-02-21 18:39 UTC, cshoben approved these changes
Just a few questions but nothing to hold up approval

2022-02-21 18:39 UTC, cshoben commented on vcf/queryInfo.go
> +				if stringValues[j] == "." {
Can you point me in the direction of where I can see an example of this input s []string?

2022-02-21 18:39 UTC, cshoben commented on cmd/vcfFormat/table.go
> +		if len(v.Alt) > maxAlts {
How does this work if the alt is a structural variant? Where the length might be greater but it is truly only one alt? I'm wondering if len() is a good way to count alt or if parsing on the "," and counting is more accurate?

2022-02-21 18:39 UTC, cshoben commented on cmd/vcfFormat/table.go
> +	case ".": // wildcard. they never make it easy do they...
lol

2022-02-21 19:07 UTC, rimangan approved these changes

2022-02-21 19:17 UTC, rimangan requested changes
Fix -o flag

2022-02-22 16:01 UTC, craiglowe approved these changes
Great!

2022-02-22 16:31 UTC, rimangan approved these changes

2022-02-22 16:41 UTC, merged